name: bundacare
description: "BundaCare - Monitor Nutrisi Ibu Hamil"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Backend & Networking
  supabase_flutter: ^2.9.1
  dio: ^5.9.0

  # Routing
  go_router: ^16.1.0

  # Dependency Injection
  get_it: ^8.2.0

  # Utilities
  equatable: ^2.0.7
  image_picker: ^1.1.2
  camera: ^0.11.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  