name: bundacare
description: "BundaCare - Monitor Nutrisi Ibu Hamil"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Backend & Networking
  supabase_flutter: ^2.9.1
  dio: ^5.9.0

  # Routing
  go_router: ^16.1.0

  # Dependency Injection
  get_it: ^8.2.0

  # Utilities
  equatable: ^2.0.7
  image_picker: ^1.1.2
  camera: ^0.11.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.1
  path: ^1.9.1
  image: ^4.5.4

  # Style
  iconsax: ^0.0.8
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/app/
    - assets/images/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

flutter_launcher_icons:
  # Path ke file ikon utama Anda
  image_path: "assets/app/app_icon.png" 
  
  # Aktifkan untuk platform Android dan iOS
  android: true
  ios: true
  
  # (Opsional tapi direkomendasikan) Pengaturan untuk ikon adaptif di Android
  # Ini mencegah ikon Anda muncul di dalam lingkaran/kotak putih
  adaptive_icon_background: "#121212" # Warna background (misal: hitam/gelap)
  adaptive_icon_foreground: "assets/app/app_icon.png"

flutter_native_splash:
  # Konfigurasi untuk iOS dan Android di bawah versi 12
  color: "#202020"
  # background_image: "assets/app/splash_screen_background.jpg"
  image: "assets/app/splach_screen_logo.png"
  # TAMBAHKAN INI: Tampilkan branding di bagian bawah
  branding: "assets/app/branding_logo.png"

  # Konfigurasi KHUSUS untuk Android 12 dan lebih baru
  android_12:
    color: "#202020"
    image: "assets/app/splach_screen_logo.png"
    # TAMBAHKAN INI JUGA: Tampilkan branding untuk Android 12+
    branding: "assets/app/branding_logo.png"